# Generated by Django 5.0.1 on 2024-01-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_snab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductoEnContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(auto_now=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_snab.contenedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_snab.producto')),
            ],
        ),
        migrations.AddField(
            model_name='contenedor',
            name='productos',
            field=models.ManyToManyField(through='inventario_snab.ProductoEnContenedor', to='inventario_snab.producto'),
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_snab.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_snab.proveedor')),
            ],
        ),
    ]
